### PR TITLE
Js test

### PR DESCRIPTION
**Pull request by CesarCGuzman**
Merging JavaScript functionality to main

### CODE REVIEW

**Comment by CesarCGuzman** [comment]
**I've read over most of the code in this, but please make sure I'm not breaking anything that you have previously committed**

**Review by mianjoto — APPROVED** [review]
Very nice work. Everything looks clean. Soon we'll separate the drawing-canvas DOM element in the `compose-reply-scratch.html` into a separate canvas.html file that can be inherited whenever necessary.

**Comment by harshicabalu** [comment]
The code looks well organized.

**Review by harshicabalu — APPROVED** [review]
I was worried the requirements txt file was not updated but it looks updated

**Pull request merged**
